INSERT INTO PRODUCT(PRODUCTID, PRODUCTCATEGORY, PRODUCTNAME, PRODUCTDESCRIPTION, UNITS)
VALUES ('P01', 'Commercial', 'A320', 'Passenger Aircraft Family', 2);
INSERT INTO PRODUCT(PRODUCTID, PRODUCTCATEGORY, PRODUCTNAME, PRODUCTDESCRIPTION, UNITS)
VALUES ('P02', 'Commercial', 'A380', 'Passenger Aircraft Family', 3);
INSERT INTO PRODUCT(PRODUCTID, PRODUCTCATEGORY, PRODUCTNAME, PRODUCTDESCRIPTION, UNITS)
VALUES ('P03', 'Space', 'Sentinel', 'Satellite Family', 1);
INSERT INTO PRODUCT(PRODUCTID, PRODUCTCATEGORY, PRODUCTNAME, PRODUCTDESCRIPTION, UNITS)
VALUES ('P04', 'Helicopter', 'H135', 'Light Twin', 2);
INSERT INTO PRODUCT(PRODUCTID, PRODUCTCATEGORY, PRODUCTNAME, PRODUCTDESCRIPTION, UNITS)
VALUES ('P05', 'Helicopter', 'H125', 'Intermediate Single', 3);