INSERT INTO ApplicationUser(ID, USERNAME, PASSWORD)
VALUES ('26efbfbd-1244-efbf-bdef-bfbd4f6defbf', 'test@test.com', '$2a$10$iJassOKeaT2cm8OpP2LeLOkdEAi5cGQH647jl8ATS7tS2/9wOCUuG');

INSERT INTO PRODUCT(PRODUCTID, PRODUCTCATEGORY, PRODUCTNAME, PRODUCTDESCRIPTION, UNITS)
VALUES ('P01', 'Commercial', 'A320', 'Passenger Aircraft Family', 2);
INSERT INTO PRODUCT(PRODUCTID, PRODUCTCATEGORY, PRODUCTNAME, PRODUCTDESCRIPTION, UNITS)
VALUES ('P02', 'Commercial', 'A380', 'Passenger Aircraft Family', 3);
INSERT INTO PRODUCT(PRODUCTID, PRODUCTCATEGORY, PRODUCTNAME, PRODUCTDESCRIPTION, UNITS)
VALUES ('P03', 'Space', 'Sentinel', 'Satellite Family', 1);
INSERT INTO PRODUCT(PRODUCTID, PRODUCTCATEGORY, PRODUCTNAME, PRODUCTDESCRIPTION, UNITS)
VALUES ('P04', 'Helicopter', 'H135', 'Light Twin', 2);
INSERT INTO PRODUCT(PRODUCTID, PRODUCTCATEGORY, PRODUCTNAME, PRODUCTDESCRIPTION, UNITS)
VALUES ('P05', 'Helicopter', 'H125', 'Intermediate Single', 3);